layer_config:
    Input:
        E:
            size: 2
    Output:
        E:
            size: 4
            activation: relu
            include_bias: true
            bias_learning_rule: BackpropBias
            bias_learning_rule_kwargs:
                learning_rate: 0.000494197567654425
projection_config:
    Output:
        E:
            Input:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                    - 5.386548065293654
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.08158367762594287
training_kwargs:
    tau: 1
    forward_steps: 1
    backward_steps: 1
    learning_rate: 0.2
    verbose: false
    optimizer: SGD
