layer_config:
    Input:
        E:
            size: 2
    H1:
        E:
            size: 128
            activation: relu
            include_bias: true
            bias_learning_rule: BackpropBias
            bias_learning_rule_kwargs:
                learning_rate: 0.008451149236900886
        SomaI:
            size: 32
            activation: relu
    H2:
        E:
            size: 32
            activation: relu
            include_bias: true
            bias_learning_rule: BackpropBias
            bias_learning_rule_kwargs:
                learning_rate: 0.008451149236900886
        SomaI:
            size: 8
            activation: relu
    Output:
        E:
            size: 4
            activation: relu
            include_bias: true
            bias_learning_rule: BackpropBias
            bias_learning_rule_kwargs:
                learning_rate: 0.012947926415502598
        SomaI:
            size: 4
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.3272180408302083
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1769523365865042
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 4.708083116173457
                    weight_bounds:
                    - null
                    - 0
                    direction: R
                    learning_rule: null
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.0646298621999981
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.7308804739762219
                    weight_bounds:
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.9855959333563546
                    weight_bounds:
                    - null
                    - 0.0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 5.183393888582326
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1769523365865042
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.2739710821473262
                    weight_bounds:
                    - null
                    - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.3865583102791006
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.6920399968903772
                    weight_bounds:
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.6564037734849306
                    weight_bounds:
                    - null
                    - 0.0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 5.977812184651836
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.6722278010177094
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.7629930575686048
                    weight_bounds:
                    - null
                    - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.2899382496765948
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.4600401572902482
                    weight_bounds:
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.5591878259608454
                    weight_bounds:
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 3
    learning_rate: 0.2
    verbose: false
    optimizer: SGD
