layer_config:
    Input:
        E:
            size: 2
    H1:
        E:
            size: 128
            activation: relu
            include_bias: true
            bias_learning_rule: DendriticLossBias
            bias_learning_rule_kwargs:
                learning_rate: 0.03275126839265602
        SomaI:
            size: 32
            activation: relu
            include_bias: true
        DendI:
            size: 32
            activation: relu
    H2:
        E:
            size: 32
            activation: relu
            include_bias: true
            bias_learning_rule: DendriticLossBias
            bias_learning_rule_kwargs:
                learning_rate: 0.013977854661972704
        SomaI:
            size: 8
            activation: relu
            include_bias: true
        DendI:
            size: 8
            activation: relu
    Output:
        E:
            size: 4
            activation: relu
            include_bias: true
            bias_learning_rule: DendriticLossBias
            bias_learning_rule_kwargs:
                learning_rate: 0.015316572622116683
        SomaI:
            size: 4
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.655152668731997
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: BP_like_2E
                    learning_rule_kwargs:
                        learning_rate: 0.05927861939540718
                        max_pop_fraction: 1.0
                        stochastic: false
                        relu_gate: true
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.3762007882059437
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.959688885606248
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.23902813453592464
            H2:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    weight_constraint: clone_weight
                    weight_constraint_kwargs:
                        source: H2.E.H1.E
                        transpose: true
                        scale: 0.28363402929599085
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 4.83064121308908
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.1972305582784166
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.7222637890950936
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 44.198173885362024
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.23112958577442733
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 2.053392048215843
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.1091450919272502
                        forward_only: true
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.2522866159254504
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: BP_like_2E
                    learning_rule_kwargs:
                        learning_rate: 0.05927861939540718
                        max_pop_fraction: 1.0
                        stochastic: false
                        relu_gate: true
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.40298304433799
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.1392241660884075
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.23902813453592464
            Output:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    weight_constraint: clone_weight
                    weight_constraint_kwargs:
                        source: Output.E.H2.E
                        transpose: true
                        scale: 0.5228065823663117
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.4496403536677636
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.38275746755229534
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.0970014237889494
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 19.823838047193487
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.23112958577442733
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.362456465227771
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.1091450919272502
                        forward_only: true
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 8.660870512439395
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: BP_like_2E
                    learning_rule_kwargs:
                        learning_rate: 0.11152115625857616
                        max_pop_fraction: 1.0
                        stochastic: false
                        relu_gate: true
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.8170014093520563
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.4447950558762553
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.029497220727730422
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.3373441240654764
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728

# After optimization, accuracy: 83.5%