layer_config:
    Input:
        E:
            size: 2
    H1:
        E:
            size: 128
            activation: relu
            include_bias: true
            bias_learning_rule: Backprop
            bias_learning_rule_kwargs:
                learning_rate: 0.0023723741273216116
        SomaI:
            size: 32
            activation: relu
    H2:
        E:
            size: 32
            activation: relu
            include_bias: true
            bias_learning_rule: Backprop
            bias_learning_rule_kwargs:
                learning_rate: 0.002384074673608417
        SomaI:
            size: 8
            activation: relu
    Output:
        E:
            size: 4
            activation: relu
            include_bias: true
            bias_learning_rule: Backprop
            bias_learning_rule_kwargs:
                learning_rate: 0.008060654677551906
        SomaI:
            size: 4
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.45341851689677354
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.17515893364196825
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.07472398800493957
                    weight_bounds:
                    - null
                    - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.07836630590668701
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 4.7663561644212695
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.24925779245776264
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.808885460644247
                    weight_bounds:
                    - 0
                    - null
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.24925779245776264
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.763489999934272
                    weight_bounds:
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.15795094440809446
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.7446583559346398
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.17515893364196825
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.380940376727865
                    weight_bounds:
                    - null
                    - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.07836630590668701
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.0621350397176026
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.24925779245776264
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.3709140014148784
                    weight_bounds:
                    - 0
                    - null
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.24925779245776264
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.873646660129378
                    weight_bounds:
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.15795094440809446
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 4.135808199833921
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.370787917145862
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.18000609094170478
                    weight_bounds:
                    - null
                    - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.07836630590668701
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.0407814652680418
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.24925779245776264
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.511680233881991
                    weight_bounds:
                    - 0
                    - null
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.24925779245776264
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.6118420054156947
                    weight_bounds:
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.15795094440809446
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 3
    learning_rate: 0.2
    verbose: false
    optimizer: SGD

# After optimization, accuracy: 96.29%