layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        FBI:
            size: 50
            activation: relu
            tau: 2
        Dend_I:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        FBI:
            size: 3
            activation: relu
            tau: 2


projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: uniform_
                    weight_init_args: !!python/tuple
                        - 0
                        - 0.000725
                    weight_bounds: !!python/tuple
                        - 0
                        - 0.035
                    learning_rule: BTSP
                    learning_rule_kwargs:
                        pos_loss_th: 0.274
                        neg_loss_th: -0.0977
                        learning_rate: 0.0019
            H1:
                FBI:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 4.695
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.1
                Dend_I:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.023
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    update_phase: B
                    compartment: dend
                    learning_rule: DendriticLoss
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.08
            Output:
                E:
                    weight_init: uniform_
                    weight_init_args: !!python/tuple
                        - 0.285
                        - 1.45
                    weight_bounds: !!python/tuple
                        - 0
                        - 1.36
                    update_phase: B
                    compartment: dend
                    learning_rule: BTSP
                    learning_rule_kwargs:
                        pos_loss_th: 0.274
                        neg_loss_th: -0.0977
                        learning_rate: 0.031
        FBI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.94
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.112
                FBI:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.011
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.034
        Dend_I:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.9
                    update_phase: B
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.112
                Dend_I:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.828
                    update_phase: B
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.034
    Output:
        E:
            H1:
                E:
                    weight_init: uniform_
                    weight_init_args: !!python/tuple
                        - 0
                        - 0.004
                    weight_bounds: !!python/tuple
                        - 0
                        - 0.19
                    direction: F
                    learning_rule: BTSP
                    learning_rule_kwargs:
                        pos_loss_th: 0.497
                        neg_loss_th: -0.25
                        learning_rate: 0.04
            Output:
                FBI:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.95
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.1
        FBI:
            Output:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.534
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.112
                FBI:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.417
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.034


training_kwargs:
    tau: 3
    forward_steps: 10
    backward_steps: 0
    learning_rate: 0.95
