layer_config:
  Input:
    E:
      size: 784
  Output:
    E:
      size: 10
      activation: relu
    FBI:
      size: 5
      activation: relu


projection_config:
  Output:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 2.0530137550399634
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.006386751577165027
      Output:
        FBI:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 2.6569304380570817
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.020305333347622453
    FBI:
      Output:
        E:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 0.018374911094947044
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0429858889652221
        FBI:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 0.4636152599543221
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.09365706016459538
training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 0
  learning_rate: 0.9553728
