layer_config:
    Input:
        E:
            size: 784
    Output:
        E:
            size: 10
            activation: relu
        FBI:
            size: 3
            activation: relu
            tau: 2


projection_config:
    Output:
        E:
            Input:
                E:
                    weight_init: uniform_
                    weight_init_args: !!python/tuple
                        - 0
                        - 0.004
                    weight_bounds: !!python/tuple
                        - 0
                        - 0.19
                    direction: F
                    learning_rule: BTSP
                    learning_rule_kwargs:
                        pos_loss_th: 0.497
                        neg_loss_th: -0.25
                        learning_rate: 0.04
            Output:
                FBI:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.95
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.1
        FBI:
            Output:
                E:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.534
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.112
                FBI:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.417
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.034


training_kwargs:
    tau: 3
    forward_steps: 10
    backward_steps: 0
    learning_rate: 0.95
