layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu

projection_config:
  H1:
    E:
      Input:
        E:
          direction: F
          learning_rule: Backprop
      H1:
        SomaI:
          direction: R
          learning_rule: Backprop
    SomaI:
      Input:
        E:
          direction: F
          learning_rule: Backprop
      H1:
        E:
          direction: R
          learning_rule: Backprop
        SomaI:
          direction: R
          learning_rule: Backprop

  Output:
    E:
      H1:
        E:
          direction: F
          learning_rule: Backprop
      Output:
        SomaI:
          direction: R
          learning_rule: Backprop
    SomaI:
      H1:
        E:
          direction: F
          learning_rule: Backprop
      Output:
        E:
          direction: R
          learning_rule: Backprop
        SomaI:
          direction: R
          learning_rule: Backprop

training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 3
  learning_rate: 0.1
