network_id: 1
task_id: 2
seed_start: 1
num_instances: 5
data_seed_start: 1
supervised: True
status_bar: False
train_steps: 50000
full_analysis: True
store_history: True
store_params: True
epochs: 1
val_interval:
    - 0
    - -1
    - 250
store_history_interval:
    - 0
    - -1
    - 250
constrain_equilibration_dynamics: True