repos:
-   repo: local
    hooks:
    -   id: pytest
        name: Run tests
        entry: pytest tests/
        language: system
        pass_filenames: false
        env:
          PRE_COMMIT_RUN: 1
