[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "EIANN"
version = "0.1.0"
dependencies = []

[tool.setuptools]
packages = ["EIANN", "EIANN.rules", "EIANN.utils", "EIANN.optimize"]
package-dir = {"" = "."}

[tool.setuptools.package-data]
EIANN = ["*.yaml", "network_config/**/*.yaml"]
