layer_config:
    Input:
        E:
            size: 21
    H1:
        E:
            size: 7
            activation: softplus
            activation_kwargs:
                beta: 100
        FBI:
            size: 1
            activation: softplus
            activation_kwargs:
                beta: 100
    Output:
        E:
            size: 21
            activation: softplus
            activation_kwargs:
                beta: 100
        FBI:
            size: 1
            activation: softplus
            activation_kwargs:
                beta: 100
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
            H1:
                FBI:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
        FBI:
            H1:
                E:
                    weight_init: fill_
                    weight_init_args: !!python/tuple
                        - 1
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
            Output:
                FBI:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
        FBI:
            Output:
                E:
                    weight_init: fill_
                    weight_init_args: !!python/tuple
                        - 1
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
training_kwargs:
    tau: 3
    forward_steps: 10
    backward_steps: 5
    learning_rate: 15
    verbose: false
    optimizer: SGD
