layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
            tau: 3
        FBI:
            size: 50
            activation: relu
            tau: 2
    Output:
        E:
            size: 10
            activation: relu
            tau: 3
        FBI:
            size: 10
            activation: relu
            tau: 2
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.48517424257211
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            H1:
                FBI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.301412672000941
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.11205994529904711
        FBI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 2.9882012251682943
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.4840460345190343
                FBI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 7.3406424124335174
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.19840532653703197
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 5.36355008130285
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: SupervisedGjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            Output:
                FBI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.334091380215222
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.11205994529904711
        FBI:
            Output:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 8.229265739454137
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    update_phase: A
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.4840460345190343
                FBI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.25475779357057554
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.19840532653703197
training_kwargs:
    tau: 3
    forward_steps: 12
    backward_steps: 0
    learning_rate: 0.9553728
