bounds:
    H_E_E_learning_rate:
        - 0.0001
        - 1.
    Output_E_E_learning_rate:
        - 0.0001
        - 1.
    H1_E_Input_E_init_weight_scale:
        - 0.01
        - 10.
    H1_E_H1_E_init_weight_scale:
        - 0.01
        - 10.
    H1_E_H1_I_init_weight_scale:
        - 0.01
        - 10.
    H1_I_Input_E_init_weight_scale:
        - 0.01
        - 10.
    H1_I_H1_E_init_weight_scale:
        - 0.01
        - 10.
    H1_I_H1_I_init_weight_scale:
        - 0.01
        - 10.
    H2_E_H1_E_init_weight_scale:
        - 0.01
        - 10.
    H2_E_H2_I_init_weight_scale:
        - 0.01
        - 10.
    H2_I_H1_E_init_weight_scale:
        - 0.01
        - 10.
    H2_I_H2_E_init_weight_scale:
        - 0.01
        - 10.
    H2_I_H2_I_init_weight_scale:
        - 0.01
        - 10.
    Output_E_H2_E_init_weight_scale:
        - 0.01
        - 10.
    Output_E_Output_I_init_weight_scale:
        - 0.01
        - 10.
    Output_I_H2_E_init_weight_scale:
        - 0.01
        - 10.
    H_I_size:
        - 1.
        - 100.
    Output_I_size:
        - 1.
        - 2.
    epsilon:
        - 0.01
        - 0.999
    epsilon_decay:
        - 0.9
        - 1
    gamma:
        - 0.01
        - 0.99
default_params:
    H_I_size: 50
    Output_I_size: 2
kwargs:
    network_id: 1
    task_id: 2
    seed_start: 1
    num_instances: 5
    data_seed_start: 1
    supervised: True
    status_bar: False
    train_episodes: 1000
    treadmill_length: 23
    treadmill_cue_position: 8
    treadmill_cue_length: 3
    treadmill_reward_length: 2
    treadmill_reward_positions:
        - 15
        - 19
    treadmill_reward_values: 
        - 0
        - 1
        - -0.1
    network_config_file_path: optimize/network_config/treadmill_RL/EIANN_2_hidden_treadmill_RL_bpDale_CA1_relu_SGD_config.yaml
    val_interval:
        - -1000
        - -1
        - 10
    train_online: False
    num_training_steps_accuracy_window: 200
    constrain_equilibration_dynamics: True
    include_equilibration_dynamics_objective: True
update_context:
    - source: optimize.nested_optimize_EIANN_1_hidden_treadmill_RL
      function: update_EIANN_config_2_hidden_backprop_Dale_CA1_relu_SGD
stages:
    - source: optimize.nested_optimize_EIANN_1_hidden_treadmill_RL
      get_args_static: get_random_seeds
      compute_features: compute_features
      filter_features: filter_features
      get_objectives: get_objectives
optimization_title: EIANN_2_hidden_treadmill_RL_bpDale_CA1_relu_SGD
x0:
    H_E_E_learning_rate: 0.5
    Output_E_E_learning_rate: 0.5
    H_I_size: 50
    Output_I_size: 2
    H1_E_Input_E_init_weight_scale: 1.
    H1_E_H1_E_init_weight_scale: 1.
    H1_E_H1_I_init_weight_scale: 1.
    H1_I_Input_E_init_weight_scale: 1.
    H1_I_H1_E_init_weight_scale: 1.
    H1_I_H1_I_init_weight_scale: 1.
    H2_E_H1_E_init_weight_scale: 1.
    H2_E_H2_I_init_weight_scale: 1.
    H2_I_H1_E_init_weight_scale: 1.
    H2_I_H2_E_init_weight_scale: 1.
    H2_I_H2_I_init_weight_scale: 1.
    Output_E_H2_E_init_weight_scale: 1.2
    Output_E_Output_I_init_weight_scale: 0.1
    Output_I_H2_E_init_weight_scale: 0.1
    epsilon: 0.9
    epsilon_decay: 1
    gamma: 0.9
