layer_config:
  Input:
    E:
      size: 21
  H1:
    E:
      activation: softplus
      activation_kwargs:
        beta: 10
      size: 7
  Output:
    E:
      activation: softplus
      activation_kwargs:
        beta: 10
      size: 21
projection_config:
  H1:
    E:
      Input:
        E:
          direction: F
          learning_rule: Backprop
  Output:
    E:
      H1:
        E:
          direction: F
          learning_rule: Backprop
training_kwargs:
  backward_steps: 1
  forward_steps: 1
  learning_rate: 5.0
  optimizer: SGD
  tau: 1
  verbose: true
