layer_config:
    Input:
        E:
            size: 2
    H1:
        E:
            size: 128
            activation: relu
    H2:
        E:
            size: 32
            activation: relu
    Output:
        E:
            size: 4
            activation: relu

projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 1
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.2
    H2:
        E:
            H1:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 1
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.2
    Output:
        E:
            H2:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 1
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.2

training_kwargs:
    tau: 1
    forward_steps: 1
    backward_steps: 1
    learning_rate: 0.2
    verbose: False
    optimizer: SGD
