layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: softplus
      activation_kwargs:
        beta: 39.767014540829535
    FBI:
      size: 94
      activation: softplus
      activation_kwargs:
        beta: 39.767014540829535
      tau: 2
  Output:
    E:
      size: 10
      activation: softplus
      activation_kwargs:
        beta: 39.767014540829535
    FBI:
      size: 4
      activation: softplus
      activation_kwargs:
        beta: 39.767014540829535
      tau: 2
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.29002048862059354
      H1:
        FBI:
          weight_init: half_kaiming
          weight_bounds:
          - null
          - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0013167826472761004
    FBI:
      H1:
        E:
          weight_init: half_kaiming
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.41311180025970323
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.29002048862059354
      Output:
        FBI:
          weight_init: half_kaiming
          weight_bounds:
          - null
          - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0013167826472761004
    FBI:
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.41311180025970323
training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 3
  learning_rate: 0.2
  verbose: false
  optimizer: SGD
