layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    FBI:
      size: 1
      activation: relu
    Dend_I:
      size: 1
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    FBI:
      size: 1
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.009559108538573785
          weight_bounds: !!python/tuple
          - 0
          - 0.024578702373200017
          direction: F
          learning_rule: BTSP_2
          learning_rule_kwargs:
            pos_loss_th: 0.14354750931320523
            neg_loss_th: -0.35970549137778435
            learning_rate: 0.0426903709900178
            neg_loss_ET_discount: 0.09096472533667882
      H1:
        FBI:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - -1.0833637933576639
          direction: R
          learning_rule: null
        Dend_I:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.274133635838758
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          learning_rule: DendriticLoss_3
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.04228728446644326
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.0877084237518984
          weight_bounds: !!python/tuple
          - 0
          - 0.35387271817543703
          update_phase: B
          compartment: dend
          learning_rule: BTSP_2
          learning_rule_kwargs:
            pos_loss_th: 0.14354750931320523
            neg_loss_th: -0.35970549137778435
            learning_rate: 0.015984685097548756
            neg_loss_ET_discount: 0.09096472533667882
    FBI:
      H1:
        E:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - 0.04117221283944834
          update_phase: A
          direction: F
          learning_rule: null
    Dend_I:
      H1:
        E:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - 0.06257353686872057
          update_phase: A
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.16403068155384015
          weight_bounds: !!python/tuple
          - 0
          - 0.5281285875544331
          direction: F
          learning_rule: BTSP_2
          learning_rule_kwargs:
            pos_loss_th: 0.49985114928073665
            neg_loss_th: -0.3850179290301138
            learning_rate: 0.034692497050580445
            neg_loss_ET_discount: 0.09096472533667882
      Output:
        FBI:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - -1.46398941092602
          direction: R
          learning_rule: null
    FBI:
      Output:
        E:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - 0.08041427874813252
          update_phase: A
          direction: F
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 0
  learning_rate: 0.9553728
