layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    FBI:
      size: 1
      activation: relu
    Dend_I:
      size: 1
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    FBI:
      size: 1
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.08158763043058831
          weight_bounds: !!python/tuple
          - 0
          - 0.04686925187992291
          direction: F
          learning_rule: BTSP
          learning_rule_kwargs:
            pos_loss_th: 0.16898245277472848
            neg_loss_th: -0.06277438795649158
            learning_rate: 0.004871441746629965
      H1:
        FBI:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - -0.17971437830701092
          direction: R
          learning_rule: null
        Dend_I:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.077190865788686
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          learning_rule: DendriticLoss
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.004193355308052324
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.1541890854687007
          weight_bounds: !!python/tuple
          - 0
          - 0.9514324154918748
          update_phase: B
          compartment: dend
          learning_rule: BTSP
          learning_rule_kwargs:
            pos_loss_th: 0.16898245277472848
            neg_loss_th: -0.06277438795649158
            learning_rate: 0.0341414976734791
    FBI:
      H1:
        E:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - 0.17971437830701092
          direction: F
          learning_rule: null
    Dend_I:
      H1:
        E:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - 0.035747213382841286
          update_phase: A
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.27853519478494304
          weight_bounds: !!python/tuple
          - 0
          - 0.20036266963550747
          direction: F
          learning_rule: BTSP
          learning_rule_kwargs:
            pos_loss_th: 0.23486176147744972
            neg_loss_th: -0.31775264082400256
            learning_rate: 0.0073801903670308085
      Output:
        FBI:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - -1.9404164941763633
          direction: R
          learning_rule: null
    FBI:
      Output:
        E:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - 0.6810704841817813
          direction: F
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 0
  learning_rate: 0.9553728
