layer_config:
    Input:
        E:
            size: 750
    H1:
        E:
            size: 500
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
    Output:
        E:
            size: 10
            activation: relu

projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                    - 2.957309048541877
                    direction: F
                    learning_rule: null
    H2:
        E:
            H1:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                    - 0.30688143784094596
                    direction: F
                    learning_rule: null
    Output:
        E:
            H2:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                    - 2.093606302139006
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.02168234235499228
training_kwargs:
    tau: 1
    forward_steps: 1
    backward_steps: 1
    learning_rate: 0.2
    verbose: False
    optimizer: SGD
