layer_config:
    Input:
        E:
            size: 3
            image_dim: 32
    H1:
        E:
            population_type: Conv2D
            size: 30
            kernel_size: 5
            image_source: Input.E
            activation: relu
        MaxPoolE:
            population_type: MaxPool2D
            kernel_size: 2
            source: H1.E
    H2:
        E:
            population_type: Conv2D
            size: 30
            kernel_size: 5
            image_source: H1.MaxPoolE
            activation: relu
        MaxPoolE:
            population_type: MaxPool2D
            kernel_size: 2
            source: H2.E
        FlatE:
            population_type: flatten
            source: H2.MaxPoolE
    Output:
        E:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    projection_type: Conv2D
#                    weight_init: scaled_kaiming
#                    weight_init_args: !!python/tuple
#                    - 2.957309048541877
                    direction: F
                    learning_rule: Backprop
#                    learning_rule_kwargs:
#                        learning_rate: 0.1652392249674756
    H2:
        E:
            H1:
                MaxPoolE:
                    projection_type: Conv2D
#                    weight_init: scaled_kaiming
#                    weight_init_args: !!python/tuple
#                    - 0.30688143784094596
                    direction: F
                    learning_rule: Backprop
#                    learning_rule_kwargs:
#                        learning_rate: 0.1652392249674756
    Output:
        E:
            H2:
                FlatE:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                    - 2.093606302139006
                    direction: F
                    learning_rule: Backprop
#                    learning_rule_kwargs:
#                        learning_rate: 0.02168234235499228
training_kwargs:
    tau: 1
    forward_steps: 1
    backward_steps: 1
    learning_rate: 0.01
    verbose: false
    optimizer: SGD
