layer_config:
    Input:
        E:
            size: 21
    H1:
        E:
            size: 7
            activation: softplus
            activation_kwargs:
                beta: 100.0
        I:
            size: 7
            activation: softplus
            activation_kwargs:
                beta: 100.0
    Output:
        E:
            size: 21
            activation: softplus
            activation_kwargs:
                beta: 100.0
        I:
            size: 7
            activation: softplus
            activation_kwargs:
                beta: 100.0
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            H1:
                I:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        I:
            Input:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            H1:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - 0
                        - null
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
                I:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - null
                        - 0.
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            Output:
                I:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        I:
            H1:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            Output:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - 0
                        - null
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
                I:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds:
                        - 0
                        - null
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 3
    learning_rate: 0.2
    verbose: False
    optimizer: SGD
