layer_config:
    Input:
        E:
            size: 21
    H1:
        E:
            size: 7
            activation: softplus
            activation_kwargs:
                beta: 4.0
        FBI:
            size: 1
            activation: softplus
            activation_kwargs:
                beta: 4.0
    Output:
        E:
            size: 21
            activation: softplus
            activation_kwargs:
                beta: 4.0
        FBI:
            size: 1
            activation: softplus
            activation_kwargs:
                beta: 4.0
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            H1:
                FBI:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        FBI:
            H1:
                E:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            Output:
                FBI:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        FBI:
            Output:
                E:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
training_kwargs:
    tau: 3
    forward_steps: 10
    backward_steps: 2
    learning_rate: 0.3
    verbose: False
    optimizer: SGD
