population_templates:
  default:
    activation: relu
  E:
    projection_type: E
  I:
    projection_type: I


projection_templates:
  default:
    learning_rule: Backprop
    weight_init: half_kaining
  E:
    direction: F
    weight_bounds:
      - 0
      - None
    weight_constraint: normalize_weight
    weight_constraint_kwargs:
      scale: 9.927103
    learning_rule: GjorgjievaHebb
    learning_rule_kwargs:
      sign: 1
      learning_rate: 0.2339308
  I:
    weight_bounds:
      - None
      - 0
    weight_constraint: normalize_weight
    weight_constraint_kwargs:
      scale: 2.128817
    learning_rule: GjorgjievaHebb
    learning_rule_kwargs:
      sign: -1
      learning_rate: 0.2023946


layer_templates:
  FBI_microcircuit:
    E:
      Prev.E:
        direction: F
      Self.FBI:
        direction: R
    FBI:
      Self.E:
        direction: F
      Self.FBI:
        direction: R

layer_config:
  Input:
    E:
      size: 21
      population_type: E
  H1:
    E:
      size: 7
      population_type: E
    FBI:
      size: 7
      population_type: I
  H2:
    E:
      size: 7
      population_type: E
    FBI:
      size: 7
      population_type: I
  Output:
    E:
      size: 21
      population_type: E
    FBI:
      size: 7
      population_type: I

projection_config:
  H1:
    connectivity_type: FBI_microcircuit

  H2:
    connectivity_type: FBI_microcircuit
  Output:
    connectivity_type: FBI_microcircuit

training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 0
  learning_rate: 0.9553728
