layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    dendI:
      size: 10
      activation: relu

  Output:
    E:
      size: 10
      activation: relu


projection_config:
  H1.E:
    Input.E:
      direction: F
      learning_rule: almost_backprop2
    H1.dendI:
      direction: F
      compartment: dendrite
      learning_rule: None
      weight_constraint: clone_weight
      weight_constraint_kwargs:
        source: Output.E.H1.E
        transpose: true
        sign: -1

  H1.dendI:
    H1.E:
      direction: F
      learning_rule: None
      # weight_constraint: clone_weight
      # weight_constraint_kwargs:
      #   source: H1.E.Output.E

  Output.E:
    H1.E:
      direction: F
      learning_rule: almost_backprop2


training_kwargs:
  tau: 1
  forward_steps: 1
  backward_steps: 1
  learning_rate: 0.005
