layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    DendI:
      size: 10
      activation: relu

  Output:
    E:
      size: 10
      activation: relu


projection_config:
  H1.E:
    Input.E:
      direction: F
      learning_rule: almost_backprop2

    # Backward/dendrie projections  
    H1.DendI:
      direction: F
      compartment: dendrite
      learning_rule: None
      update_phase: B
      weight_constraint: clone_weight
      weight_constraint_kwargs:
        source: Output.E.H1.E
        transpose: true
        sign: -1
    Output.E:
      direction: F
      compartment: dendrite
      update_phase: B
      learning_rule: None
      weight_constraint: clone_weight
      weight_constraint_kwargs:
        source: Output.E.H1.E
        transpose: true

  H1.DendI:
    H1.E:
      direction: F
      learning_rule: None
      weight_constraint: clone_weight
      weight_constraint_kwargs:
        source: Output.E.H1.E

  Output.E:
    H1.E:
      direction: F
      learning_rule: almost_backprop2


training_kwargs:
  tau: 1
  forward_steps: 1
  backward_steps: 1
  learning_rate: 0.005
