layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu


projection_config:
  H1.E:
    Input.E:
      weight_init: half_kaiming
      type: exc
      direction: F
      learning_rule: Backprop
    H1.SomaI:
      weight_init: half_kaiming
      type: inh
      direction: R
      learning_rule: None

  H1.SomaI:
    H1.E:
      weight_init: half_kaiming
      type: exc
      direction: F
      learning_rule: None


  Output.E:
    H1.E:
      weight_init: half_kaiming
      type: exc
      direction: F
      learning_rule: Backprop
    Output.SomaI:
      weight_init: half_kaiming
      type: inh
      weight_init_args: [0.1]
      direction: R
      learning_rule: None

  Output.SomaI:
    Output.E:
      weight_init: half_kaiming
      type: exc
      weight_init_args: [0.1]
      direction: F
      learning_rule: None


training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 3
  learning_rate: 0.05
