layer_config:
  Input:
    E:
      size: 784

  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
    DendI:
      size: 500
      activation: relu

  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu


projection_config:
  H1.E:
    # Forward/inference projections  
    Input.E:
      weight_init: half_kaiming
      type: exc
      direction: F
      learning_rule: almost_backprop3
    H1.SomaI:
      weight_init: half_kaiming
      type: inh
      weight_init_args: [1.]
      direction: R
      learning_rule: None

    # Backward/dendrite projections  
    H1.DendI:
      weight_init: half_kaiming
      # weight_init: clone
      # weight_init_args:
      #   source: OutputE_H1E
      #   transpose: true
      #   sign: -1
      type: inh
      compartment: dendrite
      update_phase: B
      learning_rule: Backprop_dendI
      learning_rule_kwargs:
        learning_rate: 2.

  H1.SomaI:
    H1.E:
      weight_init: half_kaiming
      type: exc
      weight_init_args: [1.]
      direction: F
      learning_rule: None

  H1.DendI:
    H1.E:
      weight_init: half_kaiming
      # weight_init: clone      
      # weight_init_args:
      #   source: OutputE_H1E
      type: exc
      direction: F
      learning_rule: Backprop_dendI
      learning_rule_kwargs:
        learning_rate: 2.

  Output.E:
    H1.E:
      weight_init: half_kaiming
      type: exc
      weight_init_args: [1.1]
      direction: F
      learning_rule: almost_backprop3
    Output.SomaI:
      weight_init: half_kaiming
      type: inh
      direction: R
      learning_rule: None

  Output.SomaI:
    Output.E:
      weight_init: half_kaiming
      type: exc
      weight_init_args: [1.1]
      direction: F
      learning_rule: None


training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 3
  learning_rate: 0.05
