layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
  Output:
    E:
      size: 10
      activation: relu

projection_config:
  H1.E:
    Input.E:
      learning_rule: Backprop

  Output.E:
    H1.E:
      learning_rule: Backprop

training_kwargs:
  learning_rate: 0.025
