layer_config:
  Input:
    E:
      size: 21
  H1:
    E:
      size: 7
      activation: relu
    FBI:
      size: 7
      activation: relu
  Output:
    E:
      size: 21
      activation: relu
    FBI:
      size: 7
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 9.927103
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.2339308
      H1:
        FBI:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - -1
          - 0
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 2.128817
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.2023946
    FBI:
      H1:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 1.597438
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0594758
        FBI:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - -1
          - 0
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 5.040185
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.2982688
  Output:
    E:
      H1:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 5.066363
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.2339308
      Output:
        FBI:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - -1
          - 0
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 9.054215
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.2023946
    FBI:
      Output:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 7.67977
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0594758
        FBI:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - -1
          - 0
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 0.33433
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.2982688
training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 0
  learning_rate: 0.9553728
