layer_config:
  Input:
    E:
      size: 21

  H1:
    E:
      size: 7
      activation: softplus
    FBI:
      size: 7
      activation: softplus

  Output:
    E:
      size: 21
      activation: softplus

    FBI:
      size: 7
      activation: softplus



projection_config:
  H1:
    E:
      Input:
        E:
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
      H1:
        FBI:
          weight_bounds:
          - null
          - 0
          direction: R
          learning_rule: Backprop
    FBI:
      H1:
        E:
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
  Output:
    E:
      H1:
        E:
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
      Output:
        FBI:
          weight_bounds:
          - null
          - 0
          direction: R
          learning_rule: Backprop
    FBI:
      Output:
        E:
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop


training_kwargs:
  tau: 1
  forward_steps: 1
  backward_steps: 5
  learning_rate: 0.001
  verbose: false
  optimizer: Adam