general_params:
    activation: softplus
      beta: 4
    tau: 3
    forward_steps: 1
    backward_steps: 5
    learning_rule: backprop
    learning_rate: 0.001
    optimizer: Adam

layer_config:
    Input:
        E: 21
    H1:
        E: 7
        FBI: 7
    Output:
        E: 21
        FBI: 7

projection_config:
  H1:
      E:
          Input_E:
              type: exc
              direction: forward
          H1_FBI:
              type: inh
              direction: recurrent
      FBI:
          H1_E:
              type: exc
              direction: forward
  Output:
      E:
          H1_E:
              type: exc
              direction: forward
          Output_FBI:
              type: inh
              direction: recurrent
      FBI:
          Output_E:
              type: inh
              direction: forward