# Same as regular config, but with empty i->i projection to match Gjorgjieva architecture

layer_config:
  Input:
    E:
      size: 21
  H1:
    E:
      size: 7
      activation: softplus
      activation_kwargs:
        beta: 100
    FBI:
      size: 7
      activation: softplus
      activation_kwargs:
        beta: 100
  Output:
    E:
      size: 21
      activation: softplus
      activation_kwargs:
        beta: 100
    FBI:
      size: 7
      activation: softplus
      activation_kwargs:
        beta: 100


projection_config:
  H1:
    E:
      Input:
        E:
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: Backprop
      H1:
        FBI:
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: Backprop
    FBI:
      H1:
        E:
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: Backprop
        FBI:
          weight_init: fill_
          weight_init_args:
            - 0
          direction: R
          learning_rule: null

  Output:
    E:
      H1:
        E:
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: Backprop
      Output:
        FBI:
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: Backprop
    FBI:
      Output:
        E:
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: Backprop
        FBI:
          weight_init: fill_
          weight_init_args:
            - 0
          direction: R
          learning_rule: null


training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 2
  learning_rate: 10.
  verbose: false
  optimizer: SGD
