bounds:
    H1_E_Input_E_init_weight_scale:
        - 0.01
        - 10.
    H2_E_H1_E_init_weight_scale:
        - 0.01
        - 10.
    H_E_E_learning_rate:
        - 0.0001
        - 0.25
    H1_E_H2_E_weight_scale:
        - 0.01
        - 10.
    H2_E_Output_E_weight_scale:
        - 0.01
        - 10.
    H1_E_H1_SomaI_init_weight_scale:
        - 0.01
        - 10.
    H1_SomaI_H1_E_init_weight_scale:
        - 0.01
        - 10.
    H1_SomaI_Input_E_init_weight_scale:
        - 0.01
        - 10.
    H1_SomaI_H1_SomaI_init_weight_scale:
        - 0.01
        - 10.
    H_E_DendI_learning_rate:
        - 0.0001
        - 0.25
    H1_E_H1_DendI_init_weight_scale:
        - 0.01
        - 10.
    H1_DendI_H1_E_weight_scale:
        - 0.01
        - 10.
    H1_DendI_H1_DendI_weight_scale:
        - 0.01
        - 10.
    H2_E_H2_SomaI_init_weight_scale:
        - 0.01
        - 10.
    H2_SomaI_H2_E_init_weight_scale:
        - 0.01
        - 10.
    H2_SomaI_H1_E_init_weight_scale:
        - 0.01
        - 10.
    H2_SomaI_H2_SomaI_init_weight_scale:
        - 0.01
        - 10.
    H2_E_H2_DendI_init_weight_scale:
        - 0.01
        - 10.
    H2_DendI_H2_E_weight_scale:
        - 0.01
        - 10.
    H2_DendI_H2_DendI_weight_scale:
        - 0.01
        - 10.
    Output_E_H2_E_init_weight_scale:
        - 0.01
        - 10.
    DendI_E_learning_rate:
        - 0.0001
        - 1.
    DendI_DendI_learning_rate:
        - 0.0001
        - 1.
    Output_E_H2_E_learning_rate:
        - 0.0001
        - 0.25
    Output_E_Output_I_init_weight_scale:
        - 0.01
        - 10.
    Output_I_Output_E_init_weight_scale:
        - 0.01
        - 10.
    Output_I_H2_E_init_weight_scale:
        - 0.01
        - 10.
    Output_I_Output_I_init_weight_scale:
        - 0.01
        - 10.
    DendI_size_fraction:
        - 0.25
        - 1.
default_params:
rel_bounds:
kwargs:
    network_id: 1
    task_id: 2
    seed_start: 1
    num_instances: 5
    data_seed_start: 1
    supervised: True
    status_bar: False
    train_steps: 5600
    epochs: 1
    network_config_file_path: optimize/network_config/spiral/20250108_EIANN_2_hidden_spiral_DTP_fixed_SomaI_fixed_bias_config.yaml
    val_interval:
        - -1000
        - -1
        - 100
    num_training_steps_accuracy_window: 1000
    constrain_equilibration_dynamics: True
    include_dend_loss_objective: True
    include_equilibration_dynamics_objective: True
update_context:
    - source: optimize.nested_optimize_EIANN_spiral_2_hidden
      function: update_spiral_config_2_hidden_DTP_fixed_SomaI_fixed_bias
param_gen: PopulationAnnealing
stages:
    - source: optimize.nested_optimize_EIANN_spiral_2_hidden
      get_args_static: get_random_seeds
      compute_features: compute_features
      filter_features: filter_features
      get_objectives: get_objectives
optimization_title: EIANN_2_hidden_spiral_DTP_fixed_SomaI_fixed_bias
x0:
    H1_E_Input_E_init_weight_scale: 2.690303762957492
    H2_E_H1_E_init_weight_scale: 2.393859445643422
    H_E_E_learning_rate: 0.062331233585896956
    H1_E_H2_E_weight_scale: 0.03206643296959062
    H2_E_Output_E_weight_scale: 0.17151843742461192
    H1_E_H1_SomaI_init_weight_scale: 1.324102262234007
    H1_SomaI_H1_E_init_weight_scale: 2.317707594196894
    H1_SomaI_Input_E_init_weight_scale: 4.763243794694925
    H1_SomaI_H1_SomaI_init_weight_scale: 2.709371370447958
    H_E_DendI_learning_rate: 0.23918339264985286
    H1_E_H1_DendI_init_weight_scale: 3.9879675588090406
    H1_DendI_H1_E_weight_scale: 7.846495088949281
    H1_DendI_H1_DendI_weight_scale: 0.8459088134536445
    H2_E_H2_SomaI_init_weight_scale: 3.366059582926033
    H2_SomaI_H2_E_init_weight_scale: 0.4627583174814284
    H2_SomaI_H1_E_init_weight_scale: 1.5063150975490223
    H2_SomaI_H2_SomaI_init_weight_scale: 2.3052619791271427
    H2_E_H2_DendI_init_weight_scale: 3.169549113106818
    H2_DendI_H2_E_weight_scale: 6.945505286306374
    H2_DendI_H2_DendI_weight_scale: 0.8134971461522151
    Output_E_H2_E_init_weight_scale: 8.66216532440105
    DendI_E_learning_rate: 0.22160968396201852
    DendI_DendI_learning_rate: 0.12223801964378715
    Output_E_H2_E_learning_rate: 0.10926838378044973
    Output_E_Output_I_init_weight_scale: 0.9495776730367129
    Output_I_Output_E_init_weight_scale: 0.20024448234976977
    Output_I_H2_E_init_weight_scale: 0.4587011470780067
    Output_I_Output_I_init_weight_scale: 2.468979250006341
    DendI_size_fraction: 0.5
