layer_config:
  Input:
    E:
      size: 784

  H1:
    E:
      size: 500
      activation: relu
    FBI:
      size: 1
      activation: relu
      tau: 2
    Dend_I:
      size: 10
      activation: relu
    Dend_I_FBI:
      size: 1
      activation: relu
      tau: 2

  Output:
    E:
      size: 10
      activation: relu
    FBI:
      size: 1
      activation: relu
      tau: 2

projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args:
          - 0.5
          weight_bounds:
          - 0
          - 1.
          direction: F
          learning_rule: BTSP_2
          learning_rule_kwargs:
            pos_loss_th: 0.2
            neg_loss_th: -0.3
            learning_rate: 0.004
            neg_loss_ET_discount: 0.08
      H1:
        FBI:
          weight_init: fill_
          weight_init_args:
          - -0.7
          direction: R
          learning_rule: null
        Dend_I:
          weight_init: fill_
          weight_init_args:
          - 0.0
          weight_bounds:
          - null
          - 0
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: H1.E.Output.E
            sign: -1
          update_phase: B
          compartment: dend
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args:
          - 0.5
          weight_bounds:
          - 0
          - 2.
          update_phase: B
          compartment: dend
          learning_rule: BTSP_2
          learning_rule_kwargs:
            pos_loss_th: 0.2
            neg_loss_th: -0.3
            learning_rate: 0.02
            neg_loss_ET_discount: 0.08
    FBI:
      H1:
        E:
          weight_init: half_kaiming
          weight_bounds:
            - null
            - 0
          direction: R
          learning_rule: null

#          weight_init: fill_
#          weight_init_args:
#          - 0.14
          update_phase: A
#          direction: F
#          learning_rule: null
    Dend_I:
      H1:
        E:
          weight_init: fill_
          weight_init_args:
          - 1.0
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.H1.E
            sign: 1
          update_phase: A
          learning_rule: null
        Dend_I_FBI:
          weight_init: fill_
          weight_init_args:
          - 1.0
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.Output.FBI
            sign: 1
          update_phase: A
          direction: R
          learning_rule: null
    Dend_I_FBI:
      H1:
        Dend_I:
          weight_init: fill_
          weight_init_args:
          - 0
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.FBI.Output.E
          direction: F
          update_phase: A
          learning_rule: null

  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args:
          - 0.5
          weight_bounds:
          - 0.
          - 1.
          direction: F
          learning_rule: BTSP_2
          learning_rule_kwargs:
            pos_loss_th: 0.0
            neg_loss_th: -0.0
            learning_rate: 0.0
            neg_loss_ET_discount: 0.1
      Output:
        FBI:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - -1.25
          direction: R
          learning_rule: null
    FBI:
      Output:
        E:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - 1.
          update_phase: A
          direction: F
          learning_rule: null

training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 0
  learning_rate: 0.955
