layer_config:
  Input:
    E:
      size: 784

  H1:
    E:
      size: 500
      activation: relu
    FBI:
      size: 5
      activation: relu
      tau: 2

  H2:
    E:
      size: 500
      activation: relu
    FBI:
      size: 5
      activation: relu
      tau: 2

  Output:
    E:
      size: 10
      activation: relu
    FBI:
      size: 1
      activation: relu
      tau: 2


projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop
      H1:
        FBI:
          weight_init: half_kaiming
          weight_bounds:
            - null
            - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.005
    FBI:
      H1:
        E:
          weight_init: half_kaiming
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop
  H2:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop
      H2:
        FBI:
          weight_init: half_kaiming
          weight_bounds:
            - null
            - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.005
    FBI:
      H2:
        E:
          weight_init: half_kaiming
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop
  Output:
    E:
      H2:
        E:
          weight_init: half_kaiming
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop
      Output:
        FBI:
          weight_init: half_kaiming
          weight_bounds:
            - null
            - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.005
    FBI:
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop

training_kwargs:
  tau: 3
  forward_steps: 5
  backward_steps: 5
  learning_rate: 0.001
  verbose: False
  optimizer: SGD
