layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.612933169141554
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_1C
          learning_rule_kwargs:
            learning_rate: 0.006428706440103288
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.6053002718173593
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.H1.E
            transpose: true
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 4.469507162660811
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.3637783037695512
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.4623084818720389
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.724684696131657
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_1C
          learning_rule_kwargs:
            learning_rate: 0.013174482496658382
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.6269478964836492
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.210844374886982
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.2580862515509687
          weight_bounds: !!python/tuple
          - 0
          - null
          update_phase: A
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.0048498501571024
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
