layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
    DendI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.12991404148089228
          weight_bounds: !!python/tuple
          - 0
          - 0.14032874316790903
          direction: F
          learning_rule: BTSP_14
          learning_rule_kwargs:
            pos_loss_th: 0.189298141414129
            neg_loss_th: -0.206867752067275
            learning_rate: 0.00290339730633499
            max_pop_fraction: 0.04612537414029892
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.5858678107612243
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.5056058622272096
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          direction: R
          learning_rule: DendriticLoss_5
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.04928847140426295
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.8169150616170004
          weight_bounds: !!python/tuple
          - 0
          - 1.0256015297533174
          update_phase: B
          compartment: dend
          learning_rule: BTSP_14
          learning_rule_kwargs:
            pos_loss_th: 0.189298141414129
            neg_loss_th: -0.206867752067275
            learning_rate: 0.08040665258504397
            max_pop_fraction: 0.04612537414029892
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.290791989456463
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.612794419647722
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.1280346614940055
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
    DendI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.8681179686934052
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          update_phase: A
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.9030457311915855
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.3315073639110977
          weight_bounds: !!python/tuple
          - 0
          - 0.44839085997089173
          direction: F
          learning_rule: BTSP_14
          learning_rule_kwargs:
            pos_loss_th: 0.18353579868351752
            neg_loss_th: -0.36870478612294805
            learning_rate: 0.0032640625014827866
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.716924457810959
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 4.171502682126306
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.484291075801982
          weight_bounds: !!python/tuple
          - 0
          - null
          update_phase: A
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.5655074724863085
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
