layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
    DendI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 9.571359351701613
          weight_bounds: !!python/tuple
          - 0
          - 0.6822248228668476
          direction: F
          learning_rule: BTSP_14
          learning_rule_kwargs:
            pos_loss_th: 0.0
            neg_loss_th: 0.0
            learning_rate: 0.09665935354070375
            max_pop_fraction: 0.033174524160747176
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.1619815818433303
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.219893972292132
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          direction: R
          learning_rule: DendriticLoss_5
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.020930516793983937
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.H1.E
            transpose: true
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.514337856950156
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.27434685441112694
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.9258920984673663
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
    DendI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.07262284993871798
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          update_phase: A
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.023252779033562945
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 5.554225802873843
          weight_bounds: !!python/tuple
          - 0
          - 0.4957359977107942
          direction: F
          learning_rule: BTSP_14
          learning_rule_kwargs:
            pos_loss_th: 0.18353579868351752
            neg_loss_th: -0.36870478612294805
            learning_rate: 0.005009949818013825
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.41865365590838466
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 4.335608415958457
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.9578037036674657
          weight_bounds: !!python/tuple
          - 0
          - null
          update_phase: A
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.9199487533839871
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
