layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.7590575465338079
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BCM
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.022770758785272613
            theta_tau: 45.16405272667509
            k: 0.0034646462174697983
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.742851434438463
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.2555230975096539
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.8895081159237628
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.0167516688570013
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.856995159536128
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: Supervised_BCM_2
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.023415682808141377
            theta_tau: 12.20469619743769
            k: 0.18991924841101304
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.09322647011476227
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.9599438507843345
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.5246398267934148
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          update_phase: A
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.975207424716628
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
