layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
    DendI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.818840824229802
          weight_bounds: !!python/tuple
          - 0
          - 0.43082579695792483
          direction: F
          learning_rule: BTSP_14
          learning_rule_kwargs:
            pos_loss_th: 0.16082192644671367
            neg_loss_th: -0.26290643242538897
            learning_rate: 0.04713647312087218
            max_pop_fraction: 0.04785505033411884
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.5302512367899577
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.1672863032030434
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          direction: R
          learning_rule: DendriticLoss_5
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.015227571513338752
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.H1.E
            transpose: true
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.5753968135898213
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.3332785045695146
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.4145140572659507
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
    DendI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.5846191164163952
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          update_phase: A
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.07568659543110727
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 6.063900608468413
          weight_bounds: !!python/tuple
          - 0
          - 0.856633880191833
          direction: F
          learning_rule: BTSP_14
          learning_rule_kwargs:
            pos_loss_th: 0.18353579868351752
            neg_loss_th: -0.36870478612294805
            learning_rate: 0.006285700028560638
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.191231171617294
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.67882728794008
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.1687765397078174
          weight_bounds: !!python/tuple
          - 0
          - null
          update_phase: A
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.1702214304696104
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
