layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
    DendI:
      size: 50
      activation: relu
  H2:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
    DendI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.4915609651246434
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_5
          learning_rule_kwargs:
            learning_rate: 0.00013179926257402377
            max_pop_fraction: 0.07927828344529743
            pos_loss_th: 0.14895950556512377
            neg_loss_th: -0.12891649177853037
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.3525557677738372
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.1543156932108203
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          direction: R
          learning_rule: DendriticLoss_5
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.01674719122115887
      H2:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: H2.E.H1.E
            transpose: true
            scale: 1.0
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.2784478056253405
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.667350026135184
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.3189150552401058
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
    DendI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.4355338909077926
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          update_phase: A
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.1756256324206045
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  H2:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.876000627457584
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_5
          learning_rule_kwargs:
            learning_rate: 0.00013179926257402377
            max_pop_fraction: 0.07927828344529743
            pos_loss_th: 0.12746931514843662
            neg_loss_th: -0.4045029204979048
      H2:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.3841216527046134
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.07824501908604681
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          direction: R
          learning_rule: DendriticLoss_5
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.01674719122115887
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.H2.E
            transpose: true
            scale: 7.0710678118654755
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.19150186724055934
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.028968256764508957
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.6266390971776944
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
    DendI:
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.5044367945713253
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          update_phase: A
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.12564248955164117
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  Output:
    E:
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.5772169745431518
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_5
          learning_rule_kwargs:
            learning_rate: 0.0003211147811626931
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.43961507765630337
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.9993395578289231
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 5.531668897426685
          weight_bounds: !!python/tuple
          - 0
          - null
          update_phase: A
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.9202751726773535
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
