layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 6.633567328807781
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.34528418293986446
                    direction: F
                    learning_rule: BTSP_17
                    learning_rule_kwargs:
                        learning_rate: 0.005723200290802846
                        max_pop_fraction: 1.0
                        stochastic: false
                        neg_rate_th: 0.0
                        temporal_discount: 0.0011018314719598756
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.033301345677013
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.8764681815221294
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.007997538504796637
            H2:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    weight_constraint: clone_weight
                    weight_constraint_kwargs:
                        source: H2.E.H1.E
                        transpose: true
                        scale: 0.05269707938777077
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.1228670208431315
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.09054668498085001
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.926721136332996
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 21.06048803590989
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.17972593716292276
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 2.049963355761825
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.07054326573093803
                        forward_only: true
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.9691452431320987
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.43236418658104564
                    direction: F
                    learning_rule: BTSP_17
                    learning_rule_kwargs:
                        learning_rate: 0.005723200290802846
                        neg_rate_th: 0.0
                        stochastic: false
                        max_pop_fraction: 1.0
                        temporal_discount: 0.0011018314719598756
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.8401852245231424
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.4959557686346328
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.007997538504796637
            Output:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    weight_constraint: clone_weight
                    weight_constraint_kwargs:
                        source: Output.E.H2.E
                        transpose: true
                        scale: 5.321457449163776
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.4125824399958548
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.027369741770096455
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.3766361671316963
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 40.13953907613997
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.17972593716292276
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.469091246274823
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.07054326573093803
                        forward_only: true
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 13.457086556367953
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.887755070208662
                    direction: F
                    learning_rule: BTSP_17
                    learning_rule_kwargs:
                        learning_rate: 0.017436402629926875
                        neg_rate_th: 0.0
                        temporal_discount: 0.0011018314719598756
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.016266059642075382
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.7578396236855411
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.1382094769668838
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.8868074048980337
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728
