layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  H2:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.3417824834756154
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.39131108185597463
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.533181728235414
          weight_bounds:
          - null
          - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0016114544772369264
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.0285876282656115
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.08514800210126446
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.3539605385732712
          weight_bounds:
          - 0
          - null
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.08514800210126446
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.2781263390521735
          weight_bounds:
          - null
          - 0.0
          weight_constraint: no_autapses
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0028948036566861144
  H2:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.7159217705891364
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.39131108185597463
      H2:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.9794941665420657
          weight_bounds:
          - null
          - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0016114544772369264
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.0559707588453033
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.08514800210126446
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.1487653643642255
          weight_bounds:
          - 0
          - null
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.08514800210126446
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.4982843532157004
          weight_bounds:
          - null
          - 0.0
          weight_constraint: no_autapses
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0028948036566861144
  Output:
    E:
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.0173247817366127
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.3264900426693538
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.9428965319291286
          weight_bounds:
          - null
          - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0016114544772369264
    SomaI:
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.8591579073099564
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.08514800210126446
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.22506063682616426
          weight_bounds:
          - 0
          - null
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.08514800210126446
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.8823956574152774
          weight_bounds:
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0028948036566861144
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 3
  learning_rate: 0.2
  verbose: false
  optimizer: SGD
