layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.03126589111604868
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.190425996980815
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.4197298419217201
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.190425996980815
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.9650112451759414
                    weight_bounds:
                    - 0
                    - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.011046295251110779
training_kwargs:
    tau: 1
    forward_steps: 1
    backward_steps: 1
    learning_rate: 0.2
    verbose: false
    optimizer: SGD
