layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
    DendI:
      size: 50
      activation: relu
  H2:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
    DendI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.48172915869669997
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_2E
          learning_rule_kwargs:
            learning_rate: 0.00047024113482817015
            max_pop_fraction: 1.0
            stochastic: false
            relu_gate: true
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.2044455742897599
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.8257099393481246
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          direction: R
          learning_rule: DendriticLoss_6
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.1364907356823569
      H2:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: H2.E.H1.E
            transpose: true
            scale: 3.621972400509391
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.2493889919140179
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.8556413372515779
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.8718988736199272
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
    DendI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.2555802211682164
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.12234600426822617
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  H2:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.8272299365114381
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_2E
          learning_rule_kwargs:
            learning_rate: 0.00047024113482817015
            max_pop_fraction: 1.0
            stochastic: false
            relu_gate: true
      H2:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.3259890418755094
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 4.368044958992191
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          direction: R
          learning_rule: DendriticLoss_6
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.1364907356823569
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.H2.E
            transpose: true
            scale: 6.783703749449915
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.9280111399467794
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.39708153931770607
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.6143568313032075
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
    DendI:
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 8.103956250168471
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.699331707202313
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  Output:
    E:
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.7721269906315578
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_2E
          learning_rule_kwargs:
            learning_rate: 0.0014103670749958386
            relu_gate: true
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.3038015567359973
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H2:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.0449284620425794
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.47705298679047003
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.8171362314938817
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
