layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.1624168857645176
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_1E
          learning_rule_kwargs:
            learning_rate: 0.005006100897789962
            max_pop_fraction: 1.0
            stochastic: false
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.6148184402069403
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.H1.E
            transpose: true
            scale: 0.233597404211546
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 6.965419321963132
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.27726373889259515
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.2912631445117908
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.116912046782671
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_1E
          learning_rule_kwargs:
            learning_rate: 0.037468343649496284
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.2495499367430891
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 8.091724122366475
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.951860844963203
          weight_bounds: !!python/tuple
          - 0
          - null
          update_phase: A
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.079398632152979
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
