layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.7689278295372799
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_1E
          learning_rule_kwargs:
            learning_rate: 0.00043318283568454506
            max_pop_fraction: 1.0
            stochastic: true
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.9714249092766685
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.H1.E
            transpose: true
            scale: 27.961793854221973
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.5569163614888863
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.26909838255527707
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.2682370982603606
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 2.4709754038661416
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_1E
          learning_rule_kwargs:
            learning_rate: 0.00537605283581418
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.1290114109516756
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 4.633398933375584
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.2388148254801017
          weight_bounds: !!python/tuple
          - 0
          - null
          update_phase: A
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.367398317325531
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
