layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 52.7752042523804
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Supervised_Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.00047533005820507573
                        max_pop_fraction: 1.0
                        stochastic: false
                        relu_gate: true
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 14.609781840242432
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.003032832391530682
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.795362329453908
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.1111065553643241
            H2:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    weight_constraint: clone_weight
                    weight_constraint_kwargs:
                        source: H2.E.H1.E
                        transpose: true
                        scale: 0.13480527364599898
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 4.6282985217540915
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.008623406092015163
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 22.535649295895766
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.008623406092015163
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 12.777090797939236
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.019533532543682612
        DendI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.7490015649868489
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.09883192967454117
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 4.784325443168586
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.0006725134201674344
                        forward_only: true
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.12281522289720634
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Supervised_Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.00047533005820507573
                        max_pop_fraction: 1.0
                        stochastic: false
                        relu_gate: true
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.11455993660538125
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.003032832391530682
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.3547533854570388
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.1111065553643241
            Output:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    weight_constraint: clone_weight
                    weight_constraint_kwargs:
                        source: Output.E.H2.E
                        transpose: true
                        scale: 4.763278146356416
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 2.604761169799163
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.008623406092015163
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.0677071312421045
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.008623406092015163
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 25.81221365278078
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.019533532543682612
        DendI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.0567970104631568
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.09883192967454117
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.1319746898056021
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.0006725134201674344
                        forward_only: true
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.9719754238710994
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Supervised_Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0010298881159635145
                        max_pop_fraction: 1.0
                        stochastic: false
                        relu_gate: true
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.07658676788273487
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.003032832391530682
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.49130393368994596
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.008623406092015163
            Output:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.37720936797385307
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.008623406092015163
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.587248236116488
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.019533532543682612
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728
