layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 8.014341658902115
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.00480850675626521
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 4.598873177179511
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.019436435425348574
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 11.2810565859256
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0005466773400097006
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 11.022657310544094
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0005466773400097006
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 5.225947770516046
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.022377111153226402
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 6.079105126984942
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.00480850675626521
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.4717975814447954
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.019436435425348574
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.49648938021908
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0005466773400097006
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 4.734826351613625
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0005466773400097006
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.3304030702670917
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.022377111153226402
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.3067113578094967
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Top_Layer_Supervised_Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0019074456063618008
                        relu_gate: true
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.6104615959177042
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.019436435425348574
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.4627814634156204
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0005466773400097006
            Output:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.2126295394511524
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0005466773400097006
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.301147405165331
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.022377111153226402
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728
