layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
    DendI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.9186321089146892
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_2E
          learning_rule_kwargs:
            learning_rate: 0.0005514805936575355
            max_pop_fraction: 1.0
            stochastic: false
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.8634796394506886
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
        DendI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.03195510043455032
          weight_bounds: !!python/tuple
          - null
          - 0
          update_phase: B
          compartment: dend
          direction: R
          learning_rule: DendriticLoss_5
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.023235638849463287
      Output:
        E:
          weight_init: half_kaiming
          weight_bounds: !!python/tuple
          - 0
          - null
          weight_constraint: clone_weight
          weight_constraint_kwargs:
            source: Output.E.H1.E
            transpose: true
            scale: 0.5746795609614838
          update_phase: B
          compartment: dend
          learning_rule: null
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.8283470930320707
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.5201990339504712
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.9002755679767602
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
    DendI:
      H1:
        E:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 12.998927698972308
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.047562610430687983
            forward_only: true
        DendI:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 4.448570651385349
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.34554894031060857
            forward_only: true
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.1444853584305914
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: BP_like_2E
          learning_rule_kwargs:
            learning_rate: 0.017557514256981585
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.1260994639007371
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: null
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 7.487889287021815
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: null
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.17078560988552133
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: null
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.0351957549953754
          weight_bounds: !!python/tuple
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
