layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.203644532608368
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.7766521546880218
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.6441896859713336
          weight_bounds:
          - null
          - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.045549374141862414
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.2689218933243502
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.5335723094400662
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.8245785660763586
          weight_bounds:
          - 0
          - null
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.5335723094400662
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.7763058839538277
          weight_bounds:
          - null
          - 0.0
          weight_constraint: no_autapses
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0031415158772067605
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.0030624132536317
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.03526056175982627
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 0.42366927677472205
          weight_bounds:
          - null
          - 0
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.045549374141862414
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.612753221512516
          weight_bounds:
          - 0
          - null
          direction: F
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.5335723094400662
      Output:
        E:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 1.5617628663375285
          weight_bounds:
          - 0
          - null
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.5335723094400662
        SomaI:
          weight_init: half_kaiming
          weight_init_args: !!python/tuple
          - 3.031133586127758
          weight_bounds:
          - null
          - 0
          weight_constraint: no_autapses
          direction: R
          learning_rule: Backprop
          learning_rule_kwargs:
            learning_rate: 0.0031415158772067605
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 3
  learning_rate: 0.2
  verbose: false
  optimizer: SGD
