layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.3833900985594004
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.2740030119783384
                    direction: F
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.006032327117868199
                        max_pop_fraction: 1.0
                        stochastic: false
                        neg_rate_th: 0.0
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.9456134589756467
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.15193341882268788
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.08540976376408098
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.5676531899045412
                    weight_bounds: !!python/tuple
                    - 0.0
                    - 0.07955527159391935
                    direction: F
                    update_phase: B
                    compartment: dend
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.006032327117868199
                        max_pop_fraction: 1.0
                        stochastic: false
                        neg_rate_th: 0.0
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.8488837750429831
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.012802126402775917
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.9606672170595448
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.841544301735034
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Backprop_DendriticLoss
                    learning_rule_kwargs:
                        learning_rate: 0.07676663106100919
                        source: H1.E
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.570981659262737
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: Backprop_DendriticLoss
                    learning_rule_kwargs:
                        learning_rate: 0.043105570252459105
                        source: H1.E
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.6803515305855055
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.7000441368931727
                    direction: F
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.006032327117868199
                        neg_rate_th: 0.0
                        stochastic: false
                        max_pop_fraction: 1.0
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.9309884192768497
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.32818263739906783
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.08540976376408098
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.1682701980095447
                    weight_bounds: !!python/tuple
                    - 0.0
                    - 0.4028031070011096
                    direction: F
                    update_phase: B
                    compartment: dend
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.006032327117868199
                        max_pop_fraction: 1.0
                        stochastic: false
                        neg_rate_th: 0.0
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.7427475715300736
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.2481314021669525
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.8851208937457524
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.20044553879249324
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Backprop_DendriticLoss
                    learning_rule_kwargs:
                        learning_rate: 0.07676663106100919
                        source: H2.E
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.3881476565299686
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: Backprop_DendriticLoss
                    learning_rule_kwargs:
                        learning_rate: 0.043105570252459105
                        source: H2.E
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.1343130143869316
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.8923946404480073
                    direction: F
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.0036380494592853515
                        neg_rate_th: 0.0
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.162439249174989
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.398118644925171
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.8767013107953348
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.49660915792726723
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 3
    learning_rate: 0.9553728
