layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    SomaI:
      size: 50
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    SomaI:
      size: 10
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 8.979505314016006
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0082855269175203
      H1:
        SomaI:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 4.420755065669319
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.02582335866716333
    SomaI:
      Input:
        E:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 10.893449857663594
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0004976440140148766
      H1:
        E:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 13.717478425526746
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: R
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0004976440140148766
        SomaI:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 3.989070666159967
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.050733505677388734
  Output:
    E:
      H1:
        E:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 5.502631069466673
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: Supervised_Hebb_WeightNorm_2
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.05551723619120614
      Output:
        SomaI:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 0.30931373704957427
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.02582335866716333
    SomaI:
      H1:
        E:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 1.3876508555498575
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0004976440140148766
      Output:
        E:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 9.728800035105536
          weight_bounds: !!python/tuple
          - 0
          - null
          update_phase: A
          direction: R
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0004976440140148766
        SomaI:
          weight_init: half_kaiming
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 4.343170085257769
          weight_bounds: !!python/tuple
          - null
          - 0
          direction: R
          learning_rule: Hebb_WeightNorm
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.050733505677388734
training_kwargs:
  tau: 3
  forward_steps: 15
  backward_steps: 0
  learning_rate: 0.9553728
