layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.5073013034533822
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: BP_like_2E
                    learning_rule_kwargs:
                        learning_rate: 0.01710810722072439
                        max_pop_fraction: 1.0
                        stochastic: false
                        relu_gate: true
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.7135693808213259
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.10593288245587404
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.038278623598176374
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.09590090749427979
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.8737536423658696
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.8390095918853383
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    update_phase: A
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.2690055908271352
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.134061186217822
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.08588774306220479
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.056582868406963006
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    update_phase: A
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.005417571574235529
                        forward_only: true
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.326063290959874
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: BP_like_2E
                    learning_rule_kwargs:
                        learning_rate: 0.01710810722072439
                        max_pop_fraction: 1.0
                        stochastic: false
                        relu_gate: true
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.082710007313077
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.0116148557581848
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.038278623598176374
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.1218482004146852
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.004752016359149
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.013007888142661463
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    update_phase: A
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.775005180527675
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 17.236323325691927
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    update_phase: A
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.08588774306220479
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.5820013858776885
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.005417571574235529
                        forward_only: true
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.43225835920438016
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: BP_like_2E
                    learning_rule_kwargs:
                        learning_rate: 0.022184111740388156
                        max_pop_fraction: 1.0
                        stochastic: false
                        relu_gate: true
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.23884010141920672
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.36444823402860743
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.5277298031223785
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    update_phase: A
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.5435078623704698
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728
