layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 4.3724151032565866
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.31466649833838434
                    direction: F
                    learning_rule: BTSP_18
                    learning_rule_kwargs:
                        learning_rate: 0.01589185466692074
                        max_pop_fraction: 1.0
                        stochastic: false
                        neg_rate_th: 0.0
                        temporal_discount: 0.0028341510978418276
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.4707957347311766
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.9257438087457044
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.09694401296131766
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.570200056096231
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: B
                    compartment: dend
                    learning_rule: Top_Down_Hebbian_Temporal_Contrast_3
                    learning_rule_kwargs:
                        learning_rate: 0.010460983783327708
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.762399004751204
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.2852176829314048
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.9178410633370727
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 20.883547346832998
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    update_phase: A
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.02281123490358421
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.461507221911192
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.12895335934063137
                        forward_only: true
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.4661288791619758
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.39402478109481315
                    direction: F
                    learning_rule: BTSP_18
                    learning_rule_kwargs:
                        learning_rate: 0.01589185466692074
                        neg_rate_th: 0.0
                        stochastic: false
                        max_pop_fraction: 1.0
                        temporal_discount: 0.0028341510978418276
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.19051891056504058
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 6.669305569460378
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.09694401296131766
            Output:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.8216829097723726
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: B
                    compartment: dend
                    learning_rule: Top_Down_Hebbian_Temporal_Contrast_3
                    learning_rule_kwargs:
                        learning_rate: 0.014402020782976555
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 3.1049298608742997
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.8319536878071365
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.6975080991931857
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 37.45698757601896
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    update_phase: A
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.02281123490358421
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.650423646880132
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.12895335934063137
                        forward_only: true
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 5.920171759223266
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.35753644673931434
                    direction: F
                    learning_rule: BTSP_18
                    learning_rule_kwargs:
                        learning_rate: 0.03628096999805194
                        neg_rate_th: 0.0
                        temporal_discount: 0.0028341510978418276
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.2141071948260806
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.3533931668909334
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.2920236482121786
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.358342514409962
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728
