layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.636047166939331
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.005530094753086432
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 5.639070609004222
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.038760606777246964
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 13.55450217107157
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0006671745202106725
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 14.216180292896203
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0006671745202106725
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 5.755790949927602
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.05227404145574587
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 6.95013552216506
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.005530094753086432
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 2.4875377260065243
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.038760606777246964
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 6.117589449135748
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0006671745202106725
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 7.320080818303871
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0006671745202106725
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 2.671585880657862
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.05227404145574587
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.1091168830399416
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Top_Layer_BP_like_2L
                    learning_rule_kwargs:
                        learning_rate: 0.01925228325960693
                        relu_gate: true
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.1380416992400213
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.038760606777246964
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 5.5863478659533605
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0006671745202106725
            Output:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.0857341234173712
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.0006671745202106725
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 2.8847808851809877
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.05227404145574587
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728
