layer_config:
  Input:
    E:
      size: 21
  H1:
    E:
      size: 7
      activation: relu
    FBI:
      size: 7
      activation: relu
  Output:
    E:
      size: 21
      activation: relu
    FBI:
      size: 7
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 4.575958783810474
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.25443478846663425
      H1:
        FBI:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - -1
          - 0
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 0.5060795025698207
          weight_bounds: !!python/tuple
          - null
          - -0.01
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0016030535397002345
    FBI:
      H1:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 0.3642072687590516
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.010018337311245601
        FBI:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - -1
          - 0
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 1.6933679168092783
          weight_bounds: !!python/tuple
          - null
          - 0.0
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.032014786757987516
  Output:
    E:
      H1:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 3.4525204297340637
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.25443478846663425
      Output:
        FBI:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - -1
          - 0
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 8.075861412856131
          weight_bounds: !!python/tuple
          - null
          - -0.01
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.0016030535397002345
    FBI:
      Output:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 6.074478663380149
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
            learning_rate: 0.010018337311245601
        FBI:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - -1
          - 0
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 0.1687297869686956
          weight_bounds: !!python/tuple
          - null
          - 0.0
          direction: R
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: -1
            learning_rate: 0.032014786757987516
training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 0
  learning_rate: 0.9553728
