layer_config:
    Input:
        E:
            size: 21
    H1:
        E:
            size: 7
            activation: softplus
            activation_kwargs:
                beta: 99.98933336685897
        FBI:
            size: 7
            activation: softplus
            activation_kwargs:
                beta: 99.98933336685897
    Output:
        E:
            size: 21
            activation: softplus
            activation_kwargs:
                beta: 99.98933336685897
        FBI:
            size: 7
            activation: softplus
            activation_kwargs:
                beta: 99.98933336685897
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 9.999370204719593
            H1:
                FBI:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 9.999150705895477
        FBI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 9.996351412635924
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 9.999370204719593
            Output:
                FBI:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 9.999150705895477
        FBI:
            Output:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 9.996351412635924
training_kwargs:
    tau: 3
    forward_steps: 10
    backward_steps: 2
    learning_rate: 0.3
    verbose: false
    optimizer: SGD
