layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        FBI:
            size: 1
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        FBI:
            size: 1
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.48517424257211
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            H1:
                FBI:
                    weight_init: fill_
                    weight_init_args:
                        - -1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule:
        FBI:
            H1:
                E:
                    weight_init: fill_
                    weight_init_args:
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule:
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 5.36355008130285
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: SupervisedGjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            Output:
                FBI:
                    weight_init: fill_
                    weight_init_args:
                        - -1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule:
        FBI:
            Output:
                E:
                    weight_init: fill_
                    weight_init_args:
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    update_phase: A
                    learning_rule:
training_kwargs:
    tau: 3
    forward_steps: 10
    backward_steps: 0
    learning_rate: 0.9553728
