# like cont_J, but with H1.E.Output.E cloned from Output.E.H1.E
layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 0.061735095235877606
                    weight_bounds: !!python/tuple
                        - 0
                        - 3.737942984542882
                    direction: F
                    learning_rule: BTSP_12_cont
                    learning_rule_kwargs:
                        learning_rate: 0.006900684389813614
            H1:
                SomaI:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 0.061041432117914914
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_5
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.015920951416174885
            Output:
                E:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    weight_constraint: clone_weight
                    weight_constraint_kwargs:
                        source: Output.E.H1.E
                        transpose: True
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            Input:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H1:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: R
                    update_phase: A
                    learning_rule: null
                DendI:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 0.15660723756451086
                    weight_bounds: !!python/tuple
                        - 0
                        - 3.1607571174129747
                    direction: F
                    learning_rule: BTSP_12_cont
                    learning_rule_kwargs:
                        learning_rate: 0.05248973408306354
            Output:
                SomaI:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H1:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    update_phase: A
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728
