layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: softplus
            activation_kwargs:
                beta: 100.0
        FBI:
            size: 50
            activation: softplus
            activation_kwargs:
                beta: 100.0
    Output:
        E:
            size: 10
            activation: softplus
            activation_kwargs:
                beta: 100.0
        FBI:
            size: 10
            activation: softplus
            activation_kwargs:
                beta: 100.0
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            H1:
                FBI:
                    weight_init: half_kaiming
                    weight_bounds:
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        FBI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1

    Output:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            Output:
                FBI:
                    weight_init: half_kaiming
                    weight_bounds:
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        FBI:
            Output:
                E:
                    weight_init: half_kaiming
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1

training_kwargs:
    tau: 3
    forward_steps: 10
    backward_steps: 2
    learning_rate: 0.2
    verbose: False
    optimizer: SGD
