layer_config:
    Input:
        E:
            size: 784
    H1:
        FFI:
            size: 1
            activation: relu
        E:
            size: 500
            activation: relu
    Output:
        FFI:
            size: 1
            activation: relu
        E:
            size: 10
            activation: relu
            output_pop: True
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaining
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.48517424257211
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            H1:
                FFI:
                    weight_init: fill_
                    weight_init_args:
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: F
                    learning_rule:
        FFI:
            Input:
                E:
                    weight_init: fill_
                    weight_init_args:
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule:
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaining
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 5.36355008130285
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            Output:
                FFI:
                    weight_init: fill_
                    weight_init_args:
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule:
        FFI:
            H1:
                E:
                    weight_init: fill_
                    weight_init_args:
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule:
training_kwargs:
    tau: 1
    forward_steps: 1
    backward_steps: 0
    learning_rate: 0.9553728
