layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    FBI:
      size: 100
      activation: relu
  H2:
    E:
      size: 500
      activation: relu
    FBI:
      size: 100
      activation: relu
  Output:
    E:
      size: 10
      activation: relu
    FBI:
      size: 10
      activation: relu


projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaining
          weight_init_args:
            - 0.1
          weight_bounds: !!python/tuple
            - 0
            - null
          direction: F
          learning_rule: Backprop
      H1:
        FBI:
          weight_init: half_kaining
          weight_init_args:
            - 0.1
          weight_bounds: !!python/tuple
            - null
            - 0
          direction: R
          learning_rule: Backprop
    FBI:
      H1:
        E:
          weight_init: half_kaining
          weight_init_args:
            - 0.1
          weight_bounds: !!python/tuple
            - 0
            - null
          direction: F
          learning_rule: Backprop
  H2:
    E:
      H1:
        E:
          weight_init: half_kaining
          weight_init_args:
            - 0.1
          weight_bounds: !!python/tuple
            - 0
            - null
          direction: F
          learning_rule: Backprop
      H2:
        FBI:
          weight_init: half_kaining
          weight_init_args:
            - 0.1
          weight_bounds: !!python/tuple
            - null
            - 0
          direction: R
          learning_rule: Backprop
    FBI:
      H2:
        E:
          weight_init: half_kaining
          weight_init_args:
            - 0.1
          weight_bounds: !!python/tuple
            - 0
            - null
          direction: F
          learning_rule: Backprop
  Output:
    E:
      H2:
        E:
          weight_init: half_kaining
          weight_init_args:
            - 0.1
          weight_bounds: !!python/tuple
            - 0
            - null
          direction: F
          learning_rule: Backprop
      Output:
        FBI:
          weight_init: half_kaining
          weight_init_args:
            - 0.1
          weight_bounds: !!python/tuple
            - null
            - 0
          direction: R
          learning_rule: Backprop
    FBI:
      Output:
        E:
          weight_init: half_kaining
          weight_init_args:
            - 0.1
          weight_bounds: !!python/tuple
            - 0
            - null
          direction: F
          learning_rule: Backprop

training_kwargs:
  tau: 1
  forward_steps: 8
  backward_steps: 5
  learning_rate: 0.0001
  verbose: False
  optimizer: SGD
