layer_config:
    Input:
        E:
            size: 784
    H1:
        FFI:
            size: 1
            activation: softplus
            activation_kwargs:
                beta: 100.0
        E:
            size: 500
            activation: softplus
            activation_kwargs:
                beta: 100.0
    Output:
        FFI:
            size: 1
            activation: softplus
            activation_kwargs:
                beta: 100.0
        E:
            size: 10
            activation: softplus
            activation_kwargs:
                beta: 100.0
            output_pop: True

projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            H1:
                FFI:
                    weight_init: half_kaining
                    weight_bounds:
                        - null
                        - 0
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        FFI:
            Input:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            Output:
                FFI:
                    weight_init: half_kaining
                    weight_bounds:
                        - null
                        - 0
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        FFI:
            H1:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
training_kwargs:
    tau: 1
    forward_steps: 1
    backward_steps: 1
    learning_rate: 0.2
    verbose: False
    optimizer: SGD
