layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
    FBI:
      size: 5
      activation: relu
      tau: 2
  Output:
    E:
      size: 10
      activation: relu
    FBI:
      size: 3
      activation: relu
      tau: 2


projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: half_kaining
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop
      H1:
        FBI:
          weight_init: half_kaining
          weight_bounds:
            - null
            - 0
          direction: R
          learning_rule: Backprop
    FBI:
      H1:
        E:
          weight_init: half_kaining
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop

  Output:
    E:
      H1:
        E:
          weight_init: half_kaining
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop
      Output:
        FBI:
          weight_init: half_kaining
          weight_bounds:
            - null
            - 0
          direction: R
          learning_rule: Backprop
    FBI:
      Output:
        E:
          weight_init: half_kaining
          weight_bounds:
            - 0
            - null
          direction: F
          learning_rule: Backprop


training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 3
  learning_rate: 0.2
  verbose: False
  optimizer: SGD
