layer_config:
  Input:
    E:
      size: 784
  H1:
    E:
      size: 500
      activation: relu
  Output:
    E:
      size: 10
      activation: relu

projection_config:
  H1:
    E:
      Input:
        E:
          direction: F
          learning_rule: Backprop
  Output:
    E:
      H1:
        E:
          direction: F
          learning_rule: Backprop


training_kwargs:
  tau: 1
  forward_steps: 1
  backward_steps: 1
  learning_rate: 0.05
  verbose: false
  optimizer: SGD
