layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: softplus
            activation_kwargs:
                beta: 100.0
        I:
            size: 5
            activation: softplus
            activation_kwargs:
                beta: 100.0
            tau: 2
    Output:
        E:
            size: 10
            activation: softplus
            activation_kwargs:
                beta: 100.0
            output_pop: True
        I:
            size: 1
            activation: softplus
            activation_kwargs:
                beta: 100.0
            tau: 2

projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            H1:
                I:
                    weight_init: half_kaining
                    weight_bounds:
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        I:
            Input:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            H1:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
    Output:
        E:
            H1:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            Output:
                I:
                    weight_init: half_kaining
                    weight_bounds:
                        - null
                        - 0
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
        I:
            H1:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1
            Output:
                E:
                    weight_init: half_kaining
                    weight_bounds:
                        - 0
                        - null
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.1

training_kwargs:
    tau: 3
    forward_steps: 10
    backward_steps: 3
    learning_rate: 0.2
    verbose: False
    optimizer: SGD
