layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        FBI:
            size: 80
            activation: relu
        Dend_I:
            size: 69
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        FBI:
            size: 1
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: uniform_
                    weight_init_args: !!python/tuple
                        - 0
                        - 0.0007254142020082574
                    weight_bounds: !!python/tuple
                        - 0
                        - 0.03504071569954073
                    learning_rule: BTSP
                    learning_rule_kwargs:
                        pos_loss_th: 0.27367018298650564
                        neg_loss_th: -0.09769687690087617
                        learning_rate: 0.0019065738282785794
            H1:
                FBI:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 4.695399793928097
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.10057821509086631
                Dend_I:
                    weight_init: half_kaining
                    weight_init_args: !!python/tuple
                        - 0.023314471348277813
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    update_phase: B
                    compartment: dend
                    learning_rule: DendriticLoss
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.08014486398061567
            Output:
                E:
                    weight_init: uniform_
                    weight_init_args: !!python/tuple
                        - 0.2850258921229028
                        - 1.4501288002805413
                    weight_bounds: !!python/tuple
                        - 0
                        - 1.3620492385462841
                    update_phase: B
                    compartment: dend
                    learning_rule: BTSP
                    learning_rule_kwargs:
                        pos_loss_th: 0.27367018298650564
                        neg_loss_th: -0.09769687690087617
                        learning_rate: 0.031043890019698626
        FBI:
            H1:
                E:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.9365358745657324
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.11190014149728734
                FBI:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.011274854270092104
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.03429497248041711
        Dend_I:
            H1:
                E:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.9032058299523145
                    update_phase: B
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.11190014149728734
                Dend_I:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.8284593480689939
                    update_phase: B
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.03429497248041711
    Output:
        E:
            H1:
                E:
                    weight_init: uniform_
                    weight_init_args: !!python/tuple
                        - 0
                        - 0.004017833517400232
                    weight_bounds: !!python/tuple
                        - 0
                        - 0.19407913661125797
                    direction: F
                    learning_rule: BTSP
                    learning_rule_kwargs:
                        pos_loss_th: 0.4974269572631268
                        neg_loss_th: -0.24746323149737456
                        learning_rate: 0.04023894401904137
            Output:
                FBI:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 3.9513644200721916
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.10057821509086631
        FBI:
            Output:
                E:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.533757433537689
                    direction: F
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.11190014149728734
                FBI:
                    weight_init: half_kaining
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 0.41673911724579205
                    direction: R
                    learning_rule: GjorgjievaHebb
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.03429497248041711
training_kwargs:
    tau: 3
    forward_steps: 10
    backward_steps: 0
    learning_rate: 0.9553728