layer_config:
  Input:
    E:
      size: 21
  H1:
    E:
      size: 7
      activation: softplus
      activation_kwargs:
        beta: 100
    FBI:
      size: 1
      activation: softplus
      activation_kwargs:
        beta: 100
  Output:
    E:
      size: 21
      activation: softplus
      activation_kwargs:
        beta: 100
    FBI:
      size: 1
      activation: softplus
      activation_kwargs:
        beta: 100

projection_config:
  H1:
    E:
      Input:
        E:
          direction: F
          learning_rule: Backprop
      H1:
        FBI:
          direction: R
          learning_rule: Backprop
    FBI:
      H1:
        E:
          direction: F
          learning_rule: Backprop
  Output:
    E:
      H1:
        E:
          direction: F
          learning_rule: Backprop
      Output:
        FBI:
          direction: R
          learning_rule: Backprop
    FBI:
      Output:
        E:
          direction: F
          learning_rule: Backprop

training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 2
  learning_rate: 10
  verbose: false
  optimizer: SGD
