layer_config:
  Input:
    E:
      size: 21
  H1:
    E:
      size: 7
      activation: relu
    FBI:
      size: 1
      activation: relu
  Output:
    E:
      size: 21
      activation: relu
    FBI:
      size: 1
      activation: relu
projection_config:
  H1:
    E:
      Input:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 5.997826
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
      H1:
        FBI:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - -0.9877346
          direction: R
          learning_rule: null
    FBI:
      H1:
        E:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - 1.0
          direction: F
          learning_rule: null
  Output:
    E:
      H1:
        E:
          weight_init: uniform_
          weight_init_args: !!python/tuple
          - 0
          - 1
          weight_constraint: normalize_weight
          weight_constraint_kwargs:
            scale: 0.4849485
          weight_bounds: !!python/tuple
          - 0
          - null
          direction: F
          learning_rule: GjorgjievaHebb
          learning_rule_kwargs:
            sign: 1
      Output:
        FBI:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - -0.1850915
          direction: R
          learning_rule: null
    FBI:
      Output:
        E:
          weight_init: fill_
          weight_init_args: !!python/tuple
          - 1
          direction: F
          learning_rule: null
training_kwargs:
  tau: 3
  forward_steps: 10
  backward_steps: 0
  learning_rate: 0.9553728
