bounds:
    H1_E_Input_E_learning_rate:
        - 0.0001
        - 1.
    Output_E_H1_E_learning_rate:
        - 0.0001
        - 1.
    E_I_learning_rate:
        - 0.0001
        - 1.
    I_E_learning_rate:
        - 0.0001
        - 1.
    I_I_learning_rate:
        - 0.0001
        - 1.
    Output_E_H1_E_weight_scale:
        - 0.01
        - 10.
    Output_E_Output_I_weight_scale:
        - 0.01
        - 10.
    Output_I_Output_E_weight_scale:
        - 0.01
        - 10.
    Output_I_H1_E_weight_scale:
        - 0.01
        - 10.
    Output_I_Output_I_weight_scale:
        - 0.01
        - 10.
    H1_E_Input_E_weight_scale:
        - 0.01
        - 10.
    H1_E_H1_I_weight_scale:
        - 0.01
        - 10.
    H1_I_H1_E_weight_scale:
        - 0.01
        - 10.
    H1_I_Input_E_weight_scale:
        - 0.01
        - 10.
    H1_I_H1_I_weight_scale:
        - 0.01
        - 10.
    H1_I_size:
        - 1
        - 100
    Output_I_size:
        - 1
        - 10
default_params:
    H1_I_size: 50
    Output_I_size: 10
kwargs:
    network_id: 1
    task_id: 2
    seed_start: 1
    num_instances: 5
    data_seed_start: 1
    supervised: True
    status_bar: False
    train_steps: 20000
    epochs: 1
    network_config_file_path: config/MNIST/20230505_EIANN_1_hidden_mnist_Supervised_Gjorgjieva_Hebb_config_F.yaml
    val_interval:
        - -2001
        - -1
        - 100
    num_training_steps_accuracy_window: 2000
    constrain_equilibration_dynamics: True
update_context:
    - source: optimize.nested_optimize_EIANN_1_hidden_mnist
      function: update_EIANN_config_1_hidden_Gjorgjieva_Hebb_F
stages:
    - source: optimize.nested_optimize_EIANN_1_hidden_mnist
      get_args_static: get_random_seeds
      compute_features: compute_features
      filter_features: filter_features
      get_objectives: get_objectives
optimization_title: EIANN_1_hidden_mnist_Supervised_Gjorgjieva_Hebb_F
x0:
    E_I_learning_rate: 0.05889725542692798
    H1_E_H1_I_weight_scale: 1.5860937017840404
    H1_E_Input_E_learning_rate: 0.005647880371398828
    H1_E_Input_E_weight_scale: 0.2800353254354707
    H1_I_H1_E_weight_scale: 3.056677478413984
    H1_I_Input_E_weight_scale: 3.056677478413984
    H1_I_H1_I_weight_scale: 2.2349494313586358
    H1_I_size: 50
    I_E_learning_rate: 0.00048379300778867
    I_I_learning_rate: 0.08373746442701452
    Output_E_H1_E_learning_rate: 0.09220619156590634
    Output_E_H1_E_weight_scale: 0.8017671837661253
    Output_E_Output_I_weight_scale: 0.4739197590895173
    Output_I_Output_E_weight_scale: 0.36606750462367517
    Output_I_H1_E_weight_scale: 0.36606750462367517
    Output_I_Output_I_weight_scale: 1.1113407626461944
    Output_I_size: 10
