# H2.E.Output.E and H1.E.H2.E learned with BTSP_16
# DendI.E and DendI.DendI learned with Backprop_DendriticLoss
# E.DendI learned with DendriticLoss_6
layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.061735095235877606
                    weight_bounds: !!python/tuple
                        - 0
                        - 3.737942984542882
                    direction: F
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.006900684389813614
                        max_pop_fraction: 1.
                        stochastic: False
                        neg_rate_th: 0.
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.061041432117914914
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.015920951416174885
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.061735095235877606
                    weight_bounds: !!python/tuple
                        - 0
                        - 3.737942984542882
                    direction: F
                    update_phase: B
                    compartment: dend
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.006900684389813614
                        max_pop_fraction: 1.
                        stochastic: False
                        neg_rate_th: 0.
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.15660723756451086
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: R
                    learning_rule: Backprop_DendriticLoss
                    learning_rule_kwargs:
                        learning_rate: 0.19840532653703197
                        source: H1.E
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.15660723756451086
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: Backprop_DendriticLoss
                    learning_rule_kwargs:
                        learning_rate: 0.19840532653703197
                        source: H1.E
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.15660723756451086
                    weight_bounds: !!python/tuple
                        - 0
                        - 3.1607571174129747
                    direction: F
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.05248973408306354
                        neg_rate_th: 0.
                        stochastic: False
                        max_pop_fraction: 1.
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.3308604685151206
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.04537932238567541
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.061735095235877606
                    weight_bounds: !!python/tuple
                        - 0
                        - 3.737942984542882
                    direction: F
                    update_phase: B
                    compartment: dend
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.006900684389813614
                        max_pop_fraction: 1.
                        stochastic: False
                        neg_rate_th: 0.
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.15660723756451086
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: R
                    learning_rule: Backprop_DendriticLoss
                    learning_rule_kwargs:
                        learning_rate: 0.19840532653703197
                        source: H2.E
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.15660723756451086
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: Backprop_DendriticLoss
                    learning_rule_kwargs:
                        learning_rate: 0.19840532653703197
                        source: H2.E
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.15660723756451086
                    weight_bounds: !!python/tuple
                        - 0
                        - 3.1607571174129747
                    direction: F
                    learning_rule: BTSP_16
                    learning_rule_kwargs:
                        learning_rate: 0.05248973408306354
                        neg_rate_th: 0.
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 3
    learning_rate: 0.9553728
