# Learn TD weights with per-synapse vectorized temporal contrast
# No DendI
layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.061735095235877606
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: BP_like_1E
                    learning_rule_kwargs:
                        learning_rate: 0.006900684389813614
                        max_pop_fraction: 1.
                        stochastic: False
                        relu_gate: True
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.061735095235877606
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    update_phase: B
                    compartment: dend
                    learning_rule: VTC_1
                    learning_rule_kwargs:
                        learning_rate: 0.1
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    update_phase: A
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.061735095235877606
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: BP_like_1E
                    learning_rule_kwargs:
                        learning_rate: 0.006900684389813614
                        max_pop_fraction: 1.
                        stochastic: False
                        relu_gate: True
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.061735095235877606
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    update_phase: B
                    compartment: dend
                    learning_rule: VTC_1
                    learning_rule_kwargs:
                        learning_rate: 0.1
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    update_phase: A
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 0.15660723756451086
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: BP_like_1E
                    learning_rule_kwargs:
                        learning_rate: 0.05248973408306354
                        relu_gate: True
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    update_phase: A
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                        - 1.
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728
