layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            tau: 2
            activation: polynomial
            activation_kwargs:
                n: 2
                a: 1.
        SomaI:
            size: 100
            tau: 1.7
            activation: polynomial
            activation_kwargs:
                n: 2
                a: 1.
    H2:
        E:
            size: 500
            tau: 2
            activation: polynomial
            activation_kwargs:
                n: 2
                a: 1.
        SomaI:
            size: 100
            tau: 1.7
            activation: polynomial
            activation_kwargs:
                n: 2
                a: 1.
    Output:
        E:
            size: 10
            tau: 2
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.48517424257211
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.48517424257211
                        autapses: True
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.301412672000941
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.11205994529904711
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.48517424257211
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 2.9882012251682943
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.4840460345190343
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 7.3406424124335174
                        autapses: True
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.19840532653703197
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.48517424257211
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.48517424257211
                        autapses: True
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.301412672000941
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.11205994529904711
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 9.48517424257211
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    direction: F
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.29434780488671874
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 2.9882012251682943
                    weight_bounds: !!python/tuple
                        - 0
                        - null
                    update_phase: A
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.4840460345190343
                SomaI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 7.3406424124335174
                        autapses: True
                    weight_bounds: !!python/tuple
                        - null
                        - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm_4
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.19840532653703197
    Output:
        E:
            H2:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 0.15660723756451086
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.29434780488671874
training_kwargs:
    forward_steps: 15
    backward_steps: 3
    learning_rate: 0.9553728
