layer_config:
    Input:
        E:
            size: 784
    Output:
        E:
            size: 10
            activation: relu

projection_config:
    Output:
        E:
            Input:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 1
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.2

training_kwargs:
    tau: 1
    forward_steps: 1
    backward_steps: 1
    learning_rate: 0.2
    verbose: False
    optimizer: SGD
