layer_config:
    Input:
        E:
            size: 784
    H1:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    H2:
        E:
            size: 500
            activation: relu
        SomaI:
            size: 50
            activation: relu
        DendI:
            size: 50
            activation: relu
    Output:
        E:
            size: 10
            activation: relu
        SomaI:
            size: 10
            activation: relu
projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.9093432896695843
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.22617085008362386
                    direction: F
                    learning_rule: BTSP_19
                    learning_rule_kwargs:
                        learning_rate: 0.004227019388924618
                        max_pop_fraction: 1.0
                        stochastic: false
                        neg_rate_th: 0.0
                        temporal_discount: 0.0005366533370376131
            H1:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.0764097476277368
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.8919220912490171
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.06098033865229452
            H2:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    weight_constraint: clone_weight
                    weight_constraint_kwargs:
                        source: H2.E.H1.E
                        transpose: true
                        scale: 0.5302655270210741
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            Input:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.3824713951940757
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.12184573186135012
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.6009875798484268
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 13.63269546529652
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.20372268686857808
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 1.838854683815819
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.16560599126845238
                        forward_only: true
    H2:
        E:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.13144554302464115
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.2832107013769023
                    direction: F
                    learning_rule: BTSP_19
                    learning_rule_kwargs:
                        learning_rate: 0.004227019388924618
                        neg_rate_th: 0.0
                        stochastic: false
                        max_pop_fraction: 1.0
                        temporal_discount: 0.0005366533370376131
            H2:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.2808300075483415
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
                DendI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.0080596333250944
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    update_phase: B
                    compartment: dend
                    direction: R
                    learning_rule: DendriticLoss_6
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.06098033865229452
            Output:
                E:
                    weight_init: half_kaiming
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    weight_constraint: clone_weight
                    weight_constraint_kwargs:
                        source: Output.E.H2.E
                        transpose: true
                        scale: 3.93333441818103
                    update_phase: B
                    compartment: dend
                    learning_rule: null
        SomaI:
            H1:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.3349079302510944
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.3534618081127228
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 1.552870392129898
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
        DendI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 55.77814153692039
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: 1
                        learning_rate: 0.20372268686857808
                        forward_only: true
                DendI:
                    weight_init: half_kaiming
                    weight_constraint: normalize_weight
                    weight_constraint_kwargs:
                        scale: 5.327721642115883
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: Hebb_WeightNorm
                    learning_rule_kwargs:
                        sign: -1
                        learning_rate: 0.16560599126845238
                        forward_only: true
    Output:
        E:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.309958086978021
                    weight_bounds: !!python/tuple
                    - 0
                    - 0.4130114392240917
                    direction: F
                    learning_rule: BTSP_19
                    learning_rule_kwargs:
                        learning_rate: 0.01920445501210893
                        neg_rate_th: 0.0
                        temporal_discount: 0.0005366533370376131
            Output:
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.7374888361458694
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    direction: R
                    learning_rule: null
        SomaI:
            H2:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.7847707708945411
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: F
                    learning_rule: null
            Output:
                E:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 0.07790595626755652
                    weight_bounds: !!python/tuple
                    - 0
                    - null
                    direction: R
                    learning_rule: null
                SomaI:
                    weight_init: half_kaiming
                    weight_init_args: !!python/tuple
                    - 2.326714866963642
                    weight_bounds: !!python/tuple
                    - null
                    - 0
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: null
training_kwargs:
    tau: 3
    forward_steps: 15
    backward_steps: 0
    learning_rate: 0.9553728
