# bash optimize_EIANN_expanse_treadmill_rl.sh optimize/optimize_config/treadmill_RL/20260428_nested_optimize_EIANN_2_hidden_treadmill_RL_van_bp_relu_SGD_config_G.yaml hidden_treadmill_van_bp_relu_SGD

layer_config:
    Input:
        E:
            size: 5
    H1:
        E:
            size: 100
            activation: relu
    H2:
        E:
            size: 100
            activation: relu
    Output:
        E:
            size: 2
            activation: linear

projection_config:
    H1:
        E:
            Input:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 1
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.2
            H1:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 1
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.2
    H2:
        E:
            H1:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 1
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.2
            H2:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 1
                    weight_constraint: no_autapses
                    direction: R
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.2
    Output:
        E:
            H2:
                E:
                    weight_init: scaled_kaiming
                    weight_init_args: !!python/tuple
                        - 1
                    direction: F
                    learning_rule: Backprop
                    learning_rule_kwargs:
                        learning_rate: 0.2

training_kwargs:
    tau: 1
    forward_steps: 1
    backward_steps: 1
    learning_rate: 0.2
    verbose: False
    optimizer: SGD
